/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GroupProps, useFrame } from '@react-three/fiber'
import { Group, PointLight, Mesh, AdditiveBlending } from 'three'

export function MinecraftTorch(props: GroupProps) {
    const group = useRef<Group>(null)
    const lightRef = useRef<PointLight>(null)
    const glowRef = useRef<Mesh>(null)
    const glowRef2 = useRef<Mesh>(null)
    const { scene } = useGLTF('/models/minecraft_torch.glb')
    // Clone the scene so we can reuse it multiple times
    const clone = useMemo(() => scene.clone(), [scene])

    // Animate the light and glow for flickering effect
    useFrame((state) => {
        const time = state.clock.elapsedTime

        if (lightRef.current) {
            // Flickering intensity between 3 and 6
            lightRef.current.intensity = 4 + Math.sin(time * 8) * 1.5 + Math.sin(time * 12) * 0.5
            // Slight color variation for more realistic flame
            const flicker = 0.9 + Math.sin(time * 10) * 0.1
            lightRef.current.color.setRGB(1, 0.6 * flicker, 0.2 * flicker)
        }

        // Animate the glow spheres
        if (glowRef.current) {
            const scale = 1 + Math.sin(time * 6) * 0.15 + Math.sin(time * 10) * 0.1
            glowRef.current.scale.setScalar(scale)
            // @ts-ignore
            if (glowRef.current.material) {
                // @ts-ignore
                glowRef.current.material.opacity = 0.4 + Math.sin(time * 8) * 0.15
            }
        }

        if (glowRef2.current) {
            const scale = 1.2 + Math.sin(time * 5 + 1) * 0.2
            glowRef2.current.scale.setScalar(scale)
            // @ts-ignore
            if (glowRef2.current.material) {
                // @ts-ignore
                glowRef2.current.material.opacity = 0.25 + Math.sin(time * 7) * 0.1
            }
        }
    })

    return (
        <group ref={group} {...props} dispose={null}>
            <primitive object={clone} />

            {/* Inner glow sphere - bright yellow */}
            <mesh ref={glowRef} position={[0, 0.55, 0]}>
                <sphereGeometry args={[0.12, 16, 16]} />
                <meshBasicMaterial
                    color="#ffcc00"
                    transparent
                    opacity={0.5}
                    blending={AdditiveBlending}
                    depthWrite={false}
                />
            </mesh>

            {/* Outer glow sphere - orange/yellow */}
            <mesh ref={glowRef2} position={[0, 0.55, 0]}>
                <sphereGeometry args={[0.2, 16, 16]} />
                <meshBasicMaterial
                    color="#ff8800"
                    transparent
                    opacity={0.3}
                    blending={AdditiveBlending}
                    depthWrite={false}
                />
            </mesh>

            {/* Outermost soft glow */}
            <mesh position={[0, 0.55, 0]}>
                <sphereGeometry args={[0.35, 16, 16]} />
                <meshBasicMaterial
                    color="#ff6600"
                    transparent
                    opacity={0.15}
                    blending={AdditiveBlending}
                    depthWrite={false}
                />
            </mesh>

            {/* Animated glowing light source */}
            <pointLight
                ref={lightRef}
                position={[0, 0.5, 0]}
                intensity={5}
                distance={8}
                color="#ffaa00"
                decay={2}
            />
            {/* Secondary glow for stronger effect */}
            <pointLight
                position={[0, 0.5, 0]}
                intensity={2}
                distance={3}
                color="#ffdd44"
                decay={2}
            />
        </group>
    )
}

useGLTF.preload('/models/minecraft_torch.glb')


